name: flight_tracker
description: A test assignment for Flutter developer.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # state management and clean architecture
  bloc: ^8.1.2
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.1
  equatable: ^2.0.5
  injectable: ^2.3.2
  get_it: ^7.6.4
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  # routeing
  auto_route: ^7.8.4
  #  Notifications
  onesignal_flutter: ^3.0.0
  # network
  connectivity_plus: ^5.0.1
  dio: ^5.3.3
  http: ^1.1.0
  async: ^2.11.0
  # local storage
  shared_preferences: ^2.2.2
  # ui
  intl: ^0.18.1
  responsive_framework: ^1.1.1
  fluttertoast: ^8.2.2
  loader_overlay: ^2.3.2
  flutter_spinkit: ^5.2.0
  flutter_advanced_drawer: ^1.3.5
  # maps
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  injectable_generator:
  auto_route_generator:
  build_runner:

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
